Events.php
changing crowdfunding icon from line-chart -> leaf
=> changing Crowdfunding icons

views/funding-overview/index.php, views/funding/index.php, views/funding/overview.php, views/marketplace/index.php, views/product/index.php, views/product/index_user.php, views/product/overview.php
This PR should fix the image stretching.
=> fix image stretching in products/crowdfunding pages

controllers/ProductController.php
@craxrev quick fix for the bug that you reported
=> tup#86 hot fix

resources/css/xcoin.css
this should fix the bug reported by **Seif** and some other
=> fix panels overlapping

controllers/FundingController.php, controllers/MarketplaceController.php, controllers/ProductController.php, views/funding/create.php, views/marketplace/sell.php, views/product/create.php
this will resolve [meta#79](https://github.com/Coinsence/meta/issues/79)
=> Preselect ccc asset in marketplace and crowdfunding forms

Events.php, Module.php, config.php, controllers/ConfigController.php, models/Asset.php, models/SpaceModuleSettings.php, views/config/snippet.php
This will resolve [meta#81](https://github.com/Coinsence/meta/issues/81)
=> Fix Meta#81

grids/AccountsGridView.php, helpers/AccountHelper.php
This will resolve [meta#97](https://github.com/Coinsence/meta/issues/97)
=> Fix Issue 97

Events.php, models/Account.php
fix delete space related accounts bug & fix crowdfunding available_amount bug
=> fix delete space bug 

Events.php, config.php, migrations/m190709_151801_investor_account.php, models/Account.php
resolving allocation new coins in account TYPE_COMMUNITY_INVESTOR when leaving an rejoin space
=> resolving allocation new coins in account TYPE_COMMUNITY_INVESTOR when leaving an rejoin space

controllers/TransactionController.php, helpers/AccountHelper.php, messages/de/overview.php, messages/en_gb/overview.php, messages/fr/overview.php, views/overview/index_space.php
- Hiding ISSUE account from accounts view list & accounts select list
- Showing Total Issued Amount in top of accounts view list page
- disabling transferring back coins to ISSUE ACCOUNT
=> Removing Issue account 

controllers/ConfigController.php, controllers/MemberSearchController.php, helpers/Utils.php, jobs/IssueScheduledTransactions.php, models/SpaceModuleBasicSettings.php, models/SpaceModuleManualSettings.php, models/SpaceModuleScheduleSettings.php, resources/js/xcoin.js, views/config/manual.php, widgets/ConfigurationMenu.php, widgets/MemberPickerField.php
add `manual` tab where you can select which users you want to allocate coins to
=> Implement manual coin allocation

controllers/MemberSearchController.php, jobs/IssueScheduledTransactions.php, models/SpaceModuleManualSettings.php, resources/js/xcoin.js, views/config/manual.php, widgets/MemberPickerField.php
With this pull request, manual coin allocation will be available to only _community investor account_ holders
=> Fix manual coin allocation

grids/AccountsGridView.php, views/overview/index_profile.php, views/overview/index_space.php
fix account owner view in account page
=> change "-" with the pic of user/space in user/space account page

.coveralls.yml, .travis.yml, .travis/setup-humhub.sh
Coveralls integration testing commits
=> Coveralls testing

Events.php, views/ethereum/index.php, views/overview/index_space.php
=> Tup#224 move Ethereum btn inside account view

resources/css/user.css
=> Tup#225 remove unnecessary margins

controllers/FundingController.php, resources/css/user.css, views/funding-overview/index.php, views/funding/details_popup.php, views/funding/index.php, views/marketplace-overview/index.php, views/marketplace/overview.php, views/product/details_popup.php
turn all links to products / funding into modal links
=> Tup#227 make product and funding details into popups

controllers/FundingController.php
fixes Coinsence/meta/issues/268
=> fix redirection after funding investment

Events.php
Introduce some small changes to top & bottom menus
=> Tup#276,277

grids/AccountsGridView.php
Update task accounts  gridview
=> Funding account related to task after campaign cancellation

controllers/ChallengeController.php, controllers/FundingController.php, migrations/m210729_190159_update_funding_table.php, models/Funding.php, views/challenge/overview.php, views/funding/overview.php
Adding more buttons to activate and deactivate funding and hide and publish funding
=> Tup#290 : Closing and restarting funding campaigns

controllers/ChallengeController.php, controllers/FundingController.php, controllers/MarketplaceController.php, controllers/ProductController.php, utils/ImageUtils.php, views/challenge/create.php, views/challenge/edit.php, views/challenge/index.php, views/challenge/overview.php, views/funding/details.php, views/funding/edit.php, views/funding/media.php, views/marketplace/create.php, views/marketplace/edit.php, views/marketplace/index.php, views/marketplace/overview.php, views/product/details.php, views/product/edit.php, views/product/media.php
- add custom images size validation
=> TUP#85 : optimize page loading time - cropping cover images
